export { Cta } from './catalogues'
export type { CtaProps } from './catalogues'
export { CertificationCoverage } from './certification-coverage'
export type { CertificationCoverageProps } from './certification-coverage'
export { ContactSectionForm as HomepageContactForm } from '../contact/contact-section-form'
export { ContactSection as Contact } from '../contact/contact-section'
export { Faq } from './faq'
export { HomepageHero } from './hero'
export type { HomepageHeroProps } from './hero'
export { HomepageNewsletter } from './newsletter'
export type { HomepageNewsletterProps } from './newsletter'
export { OrganicHerbs } from './organic-herbs'
export type { OrganicHerbsProps } from './organic-herbs'
export { OverlayImageCard } from './overlay-image-card'
export type { OverlayImageCardProps } from './overlay-image-card'
export { PrivateLabel } from './private-label'
export type { PrivateLabelProps } from './private-label'
export { ProductRange } from './product-range'
export type { ProductRangeProps } from './product-range'
export { ProofPoints } from './proof-points'
export type { ProofPointsProps } from './proof-points'
export { SupplyChain } from './supply-chain'
export type { SupplyChainProps } from './supply-chain'
export { SupplyChainProtection } from './supply-chain-protection'
export type { SupplyChainProtectionProps } from './supply-chain-protection'
export { TeaJournal, TeaJournalSection } from './tea-journal'
export type { TeaJournalProps, TeaJournalSectionProps } from './tea-journal'
export { Testimonials } from './testimonials'
export type { TestimonialsProps } from './testimonials'
